/** Typed daemon event names — dot-delimited, past-tense for completed actions. */

export const EventName = {
  DAEMON_STARTED: 'daemon.started',
  DAEMON_STOPPED: 'daemon.stopped',
  DAEMON_CONFIG_RELOADED: 'daemon.config-reloaded',
  USAGE_POLLED: 'usage.polled',
  USAGE_SOURCE_CHANGED: 'usage.source-changed',
  USAGE_STALE: 'usage.stale',
  TRIGGER_FIRED: 'trigger.fired',
  TRIGGER_SKIPPED: 'trigger.skipped',
  TASK_DISPATCHED: 'task.dispatched',
  TASK_COMPLETED: 'task.completed',
  TASK_FAILED: 'task.failed',
  TASK_REQUEUED: 'task.requeued',
  TASK_SKIPPED: 'task.skipped',
  AUTH_REFRESHED: 'auth.refreshed',
  AUTH_FAILED: 'auth.failed',
  DISPATCH_QUOTA_EXHAUSTED: 'dispatch.quota-exhausted',
  PROCESS_TIMEOUT_FIRED: 'process.timeout-fired',
  PROCESS_SIGTERM_SENT: 'process.sigterm-sent',
  PROCESS_SIGTERM_FAILED: 'process.sigterm-failed',
  PROCESS_SIGKILL_SENT: 'process.sigkill-sent',
  PROCESS_SIGKILL_FAILED: 'process.sigkill-failed',
  PROCESS_CHILD_EXITED: 'process.child-exited',
  TASK_EXECUTOR_START: 'task.executor.start',
  TASK_EXECUTOR_SUCCESS: 'task.executor.success',
  TASK_EXECUTOR_FAILED: 'task.executor.failed',
  TASK_EXECUTOR_TIMEOUT: 'task.executor.timeout',
  TASK_EXECUTOR_ABORTED: 'task.executor.aborted',
  TASK_EXECUTOR_BACKEND_ERROR: 'task.executor.backend_error',
  TASK_EXECUTOR_CHILD_IDLE: 'task.executor.child-idle',
  TASK_EXECUTOR_PROC_UNAVAILABLE: 'task.executor.proc-unavailable',
  CONTAINER_RUNTIME_DETECTED: 'container.runtime-detected',
  CONTAINER_RUNTIME_UNAVAILABLE: 'container.runtime-unavailable',
  CONTAINER_RUNTIME_NOT_FOUND: 'container.runtime-not-found',
  CONTAINER_TASK_STARTED: 'container.task-started',
  CONTAINER_TASK_COMPLETED: 'container.task-completed',
  CONTAINER_REMOVE_FAILED: 'container.remove-failed',
  CONTAINER_CREDENTIALS_RESOLVED: 'container.credentials-resolved',
  CONTAINER_CREDENTIALS_MISSING: 'container.credentials-missing',
  CONTAINER_CREDENTIALS_ERROR: 'container.credentials-error',
  CONTAINER_CONFIG_FILE_MISSING: 'container.config-file-missing',
  CONTAINER_OOM_KILLED: 'container.oom-killed',
  CONTAINER_HEALTH_IDLE: 'container.health-idle',
  CONTAINER_HEALTH_STATS_FAILED: 'container.health-stats-failed',
  CONTAINER_HOST_NETWORK_MODE: 'container.host-network-mode',
  CONTAINER_FALLBACK_ACTIVATED: 'container.fallback-activated',
  CONTAINER_RUNTIME_RECOVERED: 'container.runtime-recovered',
  CONTAINER_DISPATCH_SKIPPED: 'container.dispatch-skipped',
  CONTAINER_BINARY_MOUNTED: 'container.binary-mounted',
  CONTAINER_BINARY_MOUNT_FAILED: 'container.binary-mount-failed',
  CONTAINER_MOUNT_DECISION: 'container.mount-decision',
  CONTAINER_ENV_STRIPPED: 'container.env-stripped',
  DAEMON_CONFIG_RESTART_INITIATED: 'daemon.config-restart-initiated',
  DAEMON_CONFIG_RESTART_COMPLETED: 'daemon.config-restart-completed',
  DAEMON_CONFIG_RESTART_FAILED: 'daemon.config-restart-failed',
  /** SIGKILL was sent to the orphan process; delivery is asynchronous so the name reflects what was sent, not confirmed death. */
  DAEMON_ORPHAN_KILL_SENT: 'daemon.orphan-kill-sent',
  RESULT_ARTIFACT_WRITTEN: 'result.artifact-written',
  ACTION_EXECUTED: 'action.executed',
  ACTION_FAILED: 'action.failed',
} as const;

export type EventNameValue = (typeof EventName)[keyof typeof EventName];
